SELECT
  OPSUB.PRIJMENI,
  OPSUB.JMENO,
  OKR.NAZEV,
  OBC.NAZEV,
  COBC.NAZEV,
  OPSUB.ADRESA_CPOP,
  VL.PODIL_CITATEL|| '/' ||VL.PODIL_JMENOVATEL
FROM
  P01_OPSUB      OPSUB,
  P01_OKRES      OKR,
  P01_OBEC       OBC,
  P01_CAST_OBCE  COBC,
  P01_LV         LV,
  P01_PARCELA    PARC,
  P01_VLASTNI    VL
WHERE  
  PARC.ID_KU = '%d' AND 
  PARC.PARC_TYP ='%d' AND 
  PARC.PARC_CIS='%d' AND
  PARC.PAR_POD='%d' AND
  LV.ID_KU=PARC.ID_KU AND
  LV.ID_LV=PARC.CIS_LV AND
  VL.ID_KU=LV.ID_KU AND
  VL.ID_LV=LV.ID_LV AND
  OPSUB.ID=VL.ID_OPSUB AND
  OKR.ID=OPSUB.ADRESA_OKRES AND
  OBC.ID=OPSUB.ADRESA_OBEC AND
  COBC.ID=OPSUB.ADRESA_COBCE;
